
services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    mem_limit: 256m
    cpus: 0.1

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    mem_limit: 128m
    cpus: 0.1

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/backend:/app/apps/backend:delegated
      - ./packages:/app/packages:delegated
      - ./turbo.json:/app/turbo.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./package.json:/app/package.json
      - ./.pnpm-store:/app/.pnpm-store
      - /app/apps/backend/node_modules
    working_dir: /app/apps/backend
    command: sh -c "bash ./init.sh"
    mem_limit: 384m
    cpus: 0.5

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/web:/app/apps/web:delegated      # Hot reload com código-fonte
      - ./packages:/app/packages:delegated       # Pacotes compartilhados do monorepo
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./package.json:/app/package.json
      - ./turbo.json:/app/turbo.json
      - ./.pnpm-store:/app/.pnpm-store
      - /app/apps/web/node_modules
    working_dir: /app/apps/web
    command: sh -c "pnpm install && NODE_OPTIONS='--max-old-space-size=384' pnpm dev"
    mem_limit: 768m
    cpus: 0.6

volumes:
  pgdata:
  redis_data:
  pnpm-store:
