import type { Metadata } from 'next';
import { Providers } from './providers';
import './globals.css';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        <Providers>
          <div className="max-w-6xl mx-auto px-6 py-4">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
